// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBxQ0yvlkPNsOK03AxsilXCoMhdLBdHnwU',
    appId: '1:182327174924:web:d2dc34f3255ee51aed8b29',
    messagingSenderId: '182327174924',
    projectId: 'macfit-4e657',
    authDomain: 'macfit-4e657.firebaseapp.com',
    storageBucket: 'macfit-4e657.appspot.com',
    measurementId: 'G-R1XWNREPB8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLvLymRLHr4fDiRnTQRh8dz40J9vpT7cI',
    appId: '1:182327174924:android:3e2fb077617ceef8ed8b29',
    messagingSenderId: '182327174924',
    projectId: 'macfit-4e657',
    storageBucket: 'macfit-4e657.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZRnR38J91oyWoKcks7l374PW8SWohpsI',
    appId: '1:182327174924:ios:e6e94bdb81a4dcbaed8b29',
    messagingSenderId: '182327174924',
    projectId: 'macfit-4e657',
    storageBucket: 'macfit-4e657.appspot.com',
    iosBundleId: 'com.example.flutterApplication3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZRnR38J91oyWoKcks7l374PW8SWohpsI',
    appId: '1:182327174924:ios:6f262221c93ea26aed8b29',
    messagingSenderId: '182327174924',
    projectId: 'macfit-4e657',
    storageBucket: 'macfit-4e657.appspot.com',
    iosBundleId: 'com.example.flutterApplication3.RunnerTests',
  );
}
